CREATE DATABASE DMC_XLS;

CREATE TABLE PERFIL(
IN_ID_PERFIL INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
VC_DESCRIPCION VARCHAR(30) /*UN PERFIL PARA SOLO AGREGAR, OTRO PARA TODO EL CRUD*/
);


CREATE TABLE USUARIO(
CH_ID_USUARIO CHAR(30) PRIMARY KEY NOT NULL,
VC_NOMBRE VARCHAR(30),
VC_APELLIDOS VARCHAR(100),
IN_ID_PERFIL INT,
VC_PASSWORD VARCHAR(100),
VC_EMAIL VARCHAR(100)
);

ALTER TABLE USUARIO ADD CONSTRAINT FK_PERFIL FOREIGN KEY(IN_ID_PERFIL)
REFERENCES PERFIL(IN_ID_PERFIL);

CREATE TABLE INFORME(
IN_ID_INFORME INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
VC_BANDEJA VARCHAR(30), /*SON 8 TIPOS DE BANDEJA*/
VC_REMITENTE VARCHAR(100), /*CAMPO CORREO ELECTRONICO*/
DT_FECHA_HORA DATETIME,  /*INGRESO MANUAL*/
CH_COD_CLIENTE VARCHAR(14), /* MAX 14 MIN 6*/
VC_ESTADO VARCHAR(30), /*ACTUALIZACION, NUEVO INGRESO, DEVOLUCION*/
VC_ASUNTO VARCHAR(1000),
CH_ID_USUARIO_CREACION CHAR(30),
CH_ID_USUARIO_UPDATE CHAR(30),
DT_FECHA_CREACION DATETIME, /*CAPTURADO POR EL SIST. DE MANERA AUTOMATICA AL INGRESAR DATA*/
DT_FECHA_UPDATE DATETIME
);
ALTER TABLE INFORME ADD CONSTRAINT FK_USUARIO_CREACION FOREIGN KEY(CH_ID_USUARIO_CREACION) 
REFERENCES USUARIO(CH_ID_USUARIO);
ALTER TABLE INFORME ADD CONSTRAINT FK_USUARIO_UPDATE FOREIGN KEY(CH_ID_USUARIO_UPDATE)
REFERENCES USUARIO(CH_ID_USUARIO);

-- ADD NUEVO CAMPO A TABLA INFORME
ALTER TABLE INFORME
ADD COLUMN VC_EDITADOS VARCHAR(200) AFTER VC_ASUNTO
--ADD CAMPO PRODUCTO
ALTER TABLE INFORME
ADD COLUMN VC_PRODUCTO VARCHAR(4) AFTER VC_EDITADOS
-- PROCEDIMIENTOS ALMACENADOS
CREATE PROCEDURE USP_REGISTROS_MES
()
BEGIN
	SELECT U.CH_ID_USUARIO ID_USUARIO, COUNT(INF.CH_ID_USUARIO_CREACION) AS CANTIDAD
	FROM INFORME INF LEFT JOIN  USUARIO U ON U.CH_ID_USUARIO = INF.CH_ID_USUARIO_CREACION
	WHERE MONTH(DT_FECHA_CREACION) = MONTH(CURRENT_DATE()) AND 
	YEAR(DT_FECHA_CREACION) = YEAR(CURRENT_DATE())
	GROUP BY INF.CH_ID_USUARIO_CREACION;
END

CREATE PROCEDURE USP_REGISTROS_ESTADO_MES
()
BEGIN
	SELECT CH_ID_USUARIO_CREACION,VC_ESTADO,COUNT(VC_ESTADO) AS CANTIDAD
	FROM INFORME 
	WHERE MONTH(DT_FECHA_CREACION) = MONTH(CURRENT_DATE()) AND 
	YEAR(DT_FECHA_CREACION) = YEAR(CURRENT_DATE()) 
	GROUP BY  CH_ID_USUARIO_CREACION, VC_ESTADO
	ORDER BY CH_ID_USUARIO_CREACION;
END